name: cp_link
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/ipcjs/cp_link

executables:
  cp-link: cp_link
  dart-fix-rules: dart_fix_rules
  defender-danger-list: defender_danger_list

environment:
  sdk: '>=2.17.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0

dependencies: 
  args: ^2.3.0
  path: ^1.8.1
  yaml: ^3.1.1
  yaml_edit: ^2.0.3
  tuple: ^2.0.0